### ISSUE TITLE
SIDEBAR

### ISSUE THREAD

**Issue by raulcpop** [Hutchy68/pivot#61]
### Setup

- Browsers and versions:firefox latest
- MediaWiki version:latest
- Database version:latest
- PHP version:7
- Pivot version:latest
- Extension version (if connected to the issue):

### Issue

How I can custom Sidebar?! in original Vector skin is MediaWiki:Sidebar but in Pivot does not work! Can I get some help?!

**Comment by Hutchy68** [comment]
>How I can custom Sidebar?! in original Vector skin is MediaWiki:Sidebar but in Pivot does not work! Can I get some help?!

Define not working. https://pivot.wikiproject.net/wiki/MediaWiki:Sidebar works just fine.

>I would like to modify the sidebar because in the original skin i did
>I dont want: Upload file,special pages,links etc on that bar and I would like to remove them or hide..Please help me!
>2) I would like to remove the icons from facebook,twitter,etc.
>3) I cannot use CSS.

Removing links from the sidebar's Toolbox has nothing to do with the skin. Read https://www.mediawiki.org/wiki/Manual:Interface/Sidebar and use a JS or PHP to modify Toolbox items. (Note... someone familiar with MW will still be able to enter the direct URL to go to special pages. If you need to block, use permissions and lockdown extension {which is partially still working}).

2) What? Icons are not there unless you enable AddThis. Those icons are controlled by your AddThis account.

3) Ok? Why not. MediaWiki:Common.css or MediaWiki:Pivot.css pages can be modified and using F5 or CTRL-R to reload the CSS page will force the changes to take.

**Comment by raulcpop** [comment]
Thank you Tom for fast response!!

1) I am still trying to hide some pages from toolbox like what is the link and so on..
2) I figured out how AddThis is working !
3) Common.css is working but some codes from "MediaWiki:Common.css doesnt work in Pivot" like 

.page-Main_Wiki #contentSub {
  display: none;
}

##p-Tools{display : none;}

**Comment by Hutchy68** [comment]
Tools and really the whole sidebar load specifically with `ul` (the block) and `li` the list. `li`'s could be a label too. Some of this is specific and vanilla in output because the sidebar on desktop view is the same as on mobile view. Under premise of always using **mobile first** design, by adding in a bunch of custom blocks, images and whatever could break the mobile menu. Could the output be better, yep. Just haven't had a chance to go over everything and see what can be improved more. Images would not be a priority and probably will never be. Who wants an image in an aside menu on mobile. 

So if you want to hide SpecialPages in Toolbox use

```
li#t-specialpages {
    display: none;
}
```

Upload is `li#t-upload` but doesn't display unless someone is logged in and has permissions to upload.

Use `MediaWiki:Pivot.css` to make the changes specific to Pivot skin. Common.css loads for all skins, Pivot.css would load for just Pivot.

No idea what `#P-Tools` is. In Vector `#p-tb` is the div container of the toolbox and would hide the label and all links completely. As I said in my opening the sidebar outputs as a `ul` with `li` items. The toolbox label is 
```
label#p-tb {
    display: none;
}
```
Which would hide the label only not the entire block.

**Comment by raulcpop** [comment]
Thank you !!!!!!!!!!!!!!!!!

**Comment by Hutchy68** [comment]
Closing
