### ISSUE TITLE
Echo popups in mobile view offset out of screen

### ISSUE THREAD

**Issue by poVoq** [Hutchy68/pivot#66]
### Setup

- Browsers and versions: Firefox mobile
- MediaWiki version: 1.30
- Pivot version: latest
- Extension version (if connected to the issue): Echo

### Issue
With the pivot theme the Echo extension popups are strangely offset to be partially out of the screen to the left when viewing the site in a mobile phone. This makes them effectively not usable.

**Comment by Hutchy68** [comment]
What version of Echo are you using?

**Comment by poVoq** [comment]
Latest development master from the github repository.

**Comment by Hutchy68** [comment]
You should checkout branch REL1_30, but that is broken too. Echo is a serious pain point for all custom skins. The developers kept changing code as if the extension is in continuous development without any regards for any skin but Vector. If you rotate the mobile device, the drops realign correctly and are readable. Vertical, not so much because the left position is set to a negative number in the element. 

I won't have time to look at this (my every 6 month task to FIX it) until early next week. Then I have to walk the fine line of will it break 1.27 version by fixing 1.30 version.

**Comment by kghbln** [comment]
> Echo is a serious pain point for all custom skins.

without words. I believe to remember that they send out some info a fortnight or so ago about changes ... :|

**Comment by Hutchy68** [comment]
My main issue with this group is they don’t care. All they do is say well it’s not really developed for any other skin but vector and end of discussion.

**Comment by Hutchy68** [comment]
Closing
