### ISSUE TITLE
firstHeading class and id missing

### ISSUE THREAD

**Issue by Amousey** [Hutchy68/pivot#84]
### Version 2.1.0
- MediaWiki 1.30
- ios Safari, 375px width
- Android kitkat, 800px width

### Issue

The standard **firstHeading** class and id from mediawiki are not used. Instead Pivot uses the **title** class and no id for the page headings.

There may be other standard classes missing

### Problem code 
- File: Pivot.skin.php

`<h1 class="title"><?php print $displaytitle; ?></h1>`

### Suggested fix 
`<h1 id="firstHeading" class="firstHeading"><?php print $displaytitle; ?></h1>`

**Comment by Hutchy68** [comment]
Not sure if I would change this. Just because some skins use it doesn't mean Pivot has to use it.

>There may be other standard classes missing

Did you find any? Please, post them but `firstHeading` is not a standard class and id. It is a class and id used by Vector and Monobook. Yes, other skins use it but it is not a required class or id. Anything `mw-something...` is what I would see as a standard class.

Unless someone can point out some dire, you need to use it or it breaks a lot of stuff this will be a won't fix.

**Comment by Amousey** [comment]
Of course, thanks. It's in one of the documentation pages so I mistook it for a standard one. Timeless is also using this class, which is the skin Wikipedia is moving to of course.

Thanks for your quick responses also.
